"""Initial Migrations

Revision ID: 59821156b57d
Revises: 
Create Date: 2023-07-06 17:52:00.493557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "59821156b57d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=30), nullable=True),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("pkid"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "files",
        sa.Column("resource_type", sa.String(), nullable=True),
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("pkid"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "guestusers",
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("pkid"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "sitedetails",
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("email", sa.String(length=300), nullable=True),
        sa.Column("phone", sa.String(length=300), nullable=True),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("fb", sa.String(length=300), nullable=True),
        sa.Column("tw", sa.String(length=300), nullable=True),
        sa.Column("wh", sa.String(length=300), nullable=True),
        sa.Column("ig", sa.String(length=300), nullable=True),
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("pkid"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "subscribers",
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("exported", sa.Boolean(), nullable=True),
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("pkid"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("is_email_verified", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("is_staff", sa.Boolean(), nullable=True),
        sa.Column("terms_agreement", sa.Boolean(), nullable=True),
        sa.Column("avatar_id", sa.UUID(), nullable=True),
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["avatar_id"], ["files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pkid"),
        sa.UniqueConstraint("avatar_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "jwts",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("access", sa.String(), nullable=True),
        sa.Column("refresh", sa.String(), nullable=True),
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pkid"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "listings",
        sa.Column("auctioneer_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=70), nullable=True),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column("desc", sa.Text(), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("highest_bid", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("bids_count", sa.Integer(), nullable=True),
        sa.Column("closing_date", sa.DateTime(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("image_id", sa.UUID(), nullable=True),
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["auctioneer_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["image_id"], ["files.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("pkid"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("image_id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "otps",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("code", sa.Integer(), nullable=True),
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pkid"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "reviews",
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column("show", sa.Boolean(), nullable=True),
        sa.Column("text", sa.String(length=200), nullable=True),
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pkid"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "bids",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("listing_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pkid"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("listing_id", "amount", name="unique_listing_amount_bids"),
        sa.UniqueConstraint("user_id", "listing_id", name="unique_user_listing_bids"),
    )
    op.create_table(
        "watchlists",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("listing_id", sa.UUID(), nullable=True),
        sa.Column("session_key", sa.UUID(), nullable=True),
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_key"], ["guestusers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pkid"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint(
            "session_key", "listing_id", name="unique_session_key_listing_watchlists"
        ),
        sa.UniqueConstraint(
            "user_id", "listing_id", name="unique_user_listing_watchlists"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("watchlists")
    op.drop_table("bids")
    op.drop_table("reviews")
    op.drop_table("otps")
    op.drop_table("listings")
    op.drop_table("jwts")
    op.drop_table("users")
    op.drop_table("subscribers")
    op.drop_table("sitedetails")
    op.drop_table("guestusers")
    op.drop_table("files")
    op.drop_table("categories")
    # ### end Alembic commands ###
